set -e
psql -v --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
	CREATE USER "$POSTGRES_USER" WITH PASSWORD '$POSTGRES_PASSWORD' VALID UNTIL '2023-09-30';
	CREATE DATABASE "$POSTGRES_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER";
EOSQL