FROM apache/airflow:slim-2.6.3

COPY ../.env ./.env

ENV _AIRFLOW_DB_UPGRADE=true
ENV _AIRFLOW_WWW_USER_CREATE=true
ENV _AIRFLOW_WWW_USER_USERNAME = ${AIRFLOWID}
ENV _AIRFLOW_WWW_USER_PASSWORD = ${AIRFLOWPASSWORD}


RUN airflow db init
HEALTHCHECK --interval=5m --timeout=3s CMD ["airflow", "version"]